version: '3.5'

services:
    nginx:
        container_name: nginx
        env_file:
            - .env
        build:
            context: ./docker/build/nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - redis
        networks:
            - MyNetwork

    mysql:
        container_name: mysql
        restart: always
        image: mysql:latest
        command: --init-file /docker-entrypoint-initdb.d/structure.sql
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        volumes:
            - database:/var/lib/mysql
            - ./database/initialization/structure.sql:/docker-entrypoint-initdb.d/structure.sql
        environment:
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSAL_ROOT_HOST=%
        networks:
            - MyNetwork
    redis:
        container_name: redis
        env_file:
            - .env
        hostname: symfony.redis
        image: redis
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        networks:
            - MyNetwork
volumes:
    database:
    esdata:

networks:
    MyNetwork:
        driver: bridge
        name: MyNetwork
