version: '3.5'

services:
    api-exemplo:
        container_name: ms-${APP_NAME}
        hostname: ${APP_NAME}.localhost
        restart: always
        image: "hiagosama/php-nginx:latest"
        working_dir: /var/www/html/api-exemplo
        expose:
            - "9000"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
           #- PHP_IDE_CONFIG:serverName=Xdebug
        volumes:
            - ./:/var/www/html/api-exemplo
            - ./docker/build/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - MyNetwork

networks:
    MyNetwork:
        driver: bridge
        name: MyNetwork
